modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
    modId="mcnvguns" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="MCNV Guns" #mandatory
    logoFile="examplemod.png" #optional
    credits="We are THEM" #optional
    authors="Love, Cheese and small house plants" #optional
    description='''This is a mcnv guns mod'''

[[dependencies.mcnvguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcnvguns]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcnvguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcnvguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.3,)"
    ordering="NONE"
    side="BOTH"